name: check for appointment
on:
  workflow_dispatch:
  schedule:
    - cron: "* * * * *" # This will only check every 5 minutes https://github.blog/changelog/2019-11-01-github-actions-scheduled-jobs-maximum-frequency-is-changing/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: install dependencies
      run: pip install requests bs4 twilio
    - name: run check
      run: python check.py
      env:
        TWILIO_ACCT_ID: ${{ secrets.TWILIO_ACCT_ID }}
        TWILIO_TOKEN: ${{ secrets.TWILIO_TOKEN }}
        TEST_FLAG: "True"
